### ISSUE TITLE
BLEND is not defined 

### ISSUE THREAD

**Issue by hirako2000** [dushyantahuja/Smart-Infinity-Mirror#2]
Compilation error, the variable BLEND is not defined. Is this code valid?

```c
 // currentPalette = RainbowColors_p;
  currentBlending = BLEND;
```

**Comment by hirako2000** [comment]
Updated libraries for latest arduino firmware, they  dropped old constants. Use `LINEARBLEND`

**Comment by dushyantahuja** [comment]
Yes - this is a really old repository. Please look at the code in the following repository instead:
https://github.com/dushyantahuja/ESP8266-Infinity-Mirror

**Comment by dushyantahuja** [comment]
Code updated.
