### ISSUE TITLE
Arduino UNO R3

### ISSUE THREAD

**Issue by a94marbo** [dushyantahuja/Smart-Infinity-Mirror#3]
Trying to get the code compiled but failing. Have been trying all kinds old old verisons of libs in order to get it working.

The best (fewest faults) compile I can manage is this:

```
sketch_may15asave.ino: In function 'void setup()':
sketch_may15asave:32: error: 'LINEARBLEND' was not declared in this scope
sketch_may15asave:88: error: invalid conversion from 'void (*)()' to 'void (*)(const char*)'
sketch_may15asave:88: error: initializing argument 1 of 'void SerialCommand::setDefaultHandler(void (*)(const char*))'
sketch_may15asave.ino: In function 'void loop()':
sketch_may15asave:106: error: 'LINEARBLEND' was not declared in this scope
```

Can you link/post/upload the correct versions of the libs that work with the code?

**Comment by dushyantahuja** [comment]
You could try the latest versions of all the libraries - but this code is pretty old - so I'm not sure what's been changed. 
You can also try the code from this page (Step 2):
https://www.instructables.com/id/Infinity-Mirror-Clock/

Last option - use this repository instead. 
https://github.com/dushyantahuja/ESP8266-Infinity-Mirror

**Comment by a94marbo** [comment]
It is from this page I have used the code, but using v2.1 of FastLED creates alots of errors from other libs that have been updated aswell. So I tried with older versions of those aswell, that creates alot permutations......
Will https://github.com/dushyantahuja/ESP8266-Infinity-Mirror work with an Arduino UNO R3?

**Comment by dushyantahuja** [comment]
No - that won't work. Let me try to get this running, and I'll let you know.

**Comment by dushyantahuja** [comment]
Try now - it should work with all the latest libraries (including FastLED 3.0).

**Comment by a94marbo** [comment]
Success:

```
In file included from \Arduino\Infinity_Mirror_v1\Infinity_Mirror_v1.ino:3:0:

sketch\FastLED.h:14:21: note: #pragma message: FastLED version 3.003.003

 #    pragma message "FastLED version 3.003.003"

                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Sketch uses 10300 bytes (31%) of program storage space. Maximum is 32256 bytes.
Global variables use 1146 bytes (55%) of dynamic memory, leaving 902 bytes for local variables. Maximum is 2048 bytes.
```
No errors. thanks. seems to work now.
